namespace Demo.SObjects
{
	using Apex.System;
	using ApexSharpApi.ApexApi;
	using DateTime = global::System.DateTime;

	public class DandBCompany : SObject
	{
		public bool IsDeleted {set;get;}
		public string Name {set;get;}
		public Datetime CreatedDate {set;get;}
		public string CreatedById {set;get;}
		public User CreatedBy {set;get;}
		public Datetime LastModifiedDate {set;get;}
		public string LastModifiedById {set;get;}
		public User LastModifiedBy {set;get;}
		public Datetime SystemModstamp {set;get;}
		public Datetime LastViewedDate {set;get;}
		public Datetime LastReferencedDate {set;get;}
		public string DunsNumber {set;get;}
		public string Street {set;get;}
		public string City {set;get;}
		public string State {set;get;}
		public string PostalCode {set;get;}
		public string Country {set;get;}
		public string GeocodeAccuracyStandard {set;get;}
		public Address Address {set;get;}
		public string Phone {set;get;}
		public string Fax {set;get;}
		public string CountryAccessCode {set;get;}
		public string PublicIndicator {set;get;}
		public string StockSymbol {set;get;}
		public string StockExchange {set;get;}
		public double SalesVolume {set;get;}
		public string URL {set;get;}
		public string OutOfBusiness {set;get;}
		public double EmployeesTotal {set;get;}
		public string FipsMsaCode {set;get;}
		public string FipsMsaDesc {set;get;}
		public string TradeStyle1 {set;get;}
		public string YearStarted {set;get;}
		public string MailingStreet {set;get;}
		public string MailingCity {set;get;}
		public string MailingState {set;get;}
		public string MailingPostalCode {set;get;}
		public string MailingCountry {set;get;}
		public string MailingGeocodeAccuracy {set;get;}
		public Address MailingAddress {set;get;}
		public string Latitude {set;get;}
		public string Longitude {set;get;}
		public string PrimarySic {set;get;}
		public string PrimarySicDesc {set;get;}
		public string SecondSic {set;get;}
		public string SecondSicDesc {set;get;}
		public string ThirdSic {set;get;}
		public string ThirdSicDesc {set;get;}
		public string FourthSic {set;get;}
		public string FourthSicDesc {set;get;}
		public string FifthSic {set;get;}
		public string FifthSicDesc {set;get;}
		public string SixthSic {set;get;}
		public string SixthSicDesc {set;get;}
		public string PrimaryNaics {set;get;}
		public string PrimaryNaicsDesc {set;get;}
		public string SecondNaics {set;get;}
		public string SecondNaicsDesc {set;get;}
		public string ThirdNaics {set;get;}
		public string ThirdNaicsDesc {set;get;}
		public string FourthNaics {set;get;}
		public string FourthNaicsDesc {set;get;}
		public string FifthNaics {set;get;}
		public string FifthNaicsDesc {set;get;}
		public string SixthNaics {set;get;}
		public string SixthNaicsDesc {set;get;}
		public string OwnOrRent {set;get;}
		public double EmployeesHere {set;get;}
		public string EmployeesHereReliability {set;get;}
		public string SalesVolumeReliability {set;get;}
		public string CurrencyCode {set;get;}
		public string LegalStatus {set;get;}
		public double GlobalUltimateTotalEmployees {set;get;}
		public string EmployeesTotalReliability {set;get;}
		public string MinorityOwned {set;get;}
		public string WomenOwned {set;get;}
		public string SmallBusiness {set;get;}
		public string MarketingSegmentationCluster {set;get;}
		public string ImportExportAgent {set;get;}
		public string Subsidiary {set;get;}
		public string TradeStyle2 {set;get;}
		public string TradeStyle3 {set;get;}
		public string TradeStyle4 {set;get;}
		public string TradeStyle5 {set;get;}
		public string NationalId {set;get;}
		public string NationalIdType {set;get;}
		public string UsTaxId {set;get;}
		public string GeoCodeAccuracy {set;get;}
		public int FamilyMembers {set;get;}
		public string MarketingPreScreen {set;get;}
		public string GlobalUltimateDunsNumber {set;get;}
		public string GlobalUltimateBusinessName {set;get;}
		public string ParentOrHqDunsNumber {set;get;}
		public string ParentOrHqBusinessName {set;get;}
		public string DomesticUltimateDunsNumber {set;get;}
		public string DomesticUltimateBusinessName {set;get;}
		public string LocationStatus {set;get;}
		public string CompanyCurrencyIsoCode {set;get;}
		public string Description {set;get;}
		public int FortuneRank {set;get;}
		public string IncludedInSnP500 {set;get;}
		public int PremisesMeasure {set;get;}
		public string PremisesMeasureReliability {set;get;}
		public string PremisesMeasureUnit {set;get;}
		public double EmployeeQuantityGrowthRate {set;get;}
		public double SalesTurnoverGrowthRate {set;get;}
		public string PrimarySic8 {set;get;}
		public string PrimarySic8Desc {set;get;}
		public string SecondSic8 {set;get;}
		public string SecondSic8Desc {set;get;}
		public string ThirdSic8 {set;get;}
		public string ThirdSic8Desc {set;get;}
		public string FourthSic8 {set;get;}
		public string FourthSic8Desc {set;get;}
		public string FifthSic8 {set;get;}
		public string FifthSic8Desc {set;get;}
		public string SixthSic8 {set;get;}
		public string SixthSic8Desc {set;get;}
		public int PriorYearEmployees {set;get;}
		public double PriorYearRevenue {set;get;}
	}
}
