public class ClassNoApex
{
    // Any classes in NoApex name space will be commented out in Apex and uncommented on c#.
    public static void methodOne()
    {
        //:NoApex NoApex.Serilog.LogInfo("Jay");
    }

    // Any method in NoApex name space will be commented out in Apex and uncommented on c#.
    public static void noApexMethodTwo()
    {
        {
            {
                {
                    //:NoApex NoApex.Serilog.LogInfo("Jay");
                }

                //:NoApex NoApex.Serilog.LogInfo("Jay");
            }

            //:NoApex NoApex.Serilog.LogInfo("Jay");
        }

        //:NoApex NoApex.Serilog.LogInfo("Jay");
    }
}
